
snowflake]
user = "your_snowflake_username"
password = "your_snowflake_password"
account = "your_snowflake_account"
warehouse = "your_warehouse"
database = "your_database"
schema = "your_schema"
role = "your_role"
